; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
extra_scripts = pre:scripts/platformio_version.py
build_flags =
    -D HARDWARE_SHA256=1
    -D USE_HARDWARE_SHA=1
    -O3
    -funroll-loops
    -Wl,--wrap=esp_sha

lib_deps = 
    https://github.com/Roger-random/ESP_8_BIT_composite.git
    bblanchon/ArduinoJson@^6.21.5
    https://github.com/tzapu/WiFiManager.git#v2.0.17

[env:esp32dev]
board = esp32dev

[env:wemos_d1_uno32]
board = wemos_d1_uno32
